CHANGELOG.md
doc/options.md
src/sql/magic.py
src/tests/test_magic.py

* `-m` / `--no-message` option added to suppress output message.
* The default value is False
``` python
%%sql --no-message result <<
SELECT Name FROM track LIMIT 5
```
Closes #13

suppress output message added

---

.github/workflows/ci.yaml

Adding 3.11 to CI

---

.github/workflows/ci.yaml

Revert "Adding 3.11 to CI"

---

.github/workflows/ci.yaml

Adding macOS and Python 3.11 to the CI

Adds macOS and Python 3.11

---

doc/_config.yml

Added copyright year as 2022 in the _config.yml file

Added copyright year

---

doc/_config.yml
doc/_toc.yml
doc/connecting.md
doc/howto/postgres-connect.ipynb
doc/howto/postgres-install.md

added two new sections showing how to get the postgres connector and how to connect to a running postgres instance

adds postgres instructions

---

doc/plot.md

Fixes command for histogram plotting

---

CHANGELOG.md
src/sql/plot.py
src/tests/test_telemetry.py

Resolve https://github.com/ploomber/jupysql/issues/82
Add more telemetry 
boxplot
historgram
----
:books: Documentation preview :books:: https://jupysql--89.org.readthedocs.build/en/89/

82 - More Telemetry

---

.github/workflows/ci.yaml
setup.py

1. cd script added
2. flake8 and black added to setup.py
Issue: #23 and Closes [testing CD script](https://github.com/ploomber/dummy/issues/2)
----
:books: Documentation preview :books:: https://jupysql--105.org.readthedocs.build/en/105/

CD for jupysql added

---

README.md

Changes base URL references found in readme to updated link
Closes #96 
----
:books: Documentation preview :books:: https://jupysql--103.org.readthedocs.build/en/103/

changed base urls

---

.gitignore
CHANGELOG.md
doc/_toc.yml
doc/howto/json.md

added a tutorial showing how to query JSON data with JupySQL and DuckDB
Closes #x
----
:books: Documentation preview :books:: https://jupysql--119.org.readthedocs.build/en/119/

Tutorial json

---

src/sql/connection.py
src/sql/magic.py
src/tests/conftest.py
src/tests/test_magic.py

Closes #70
----
:books: Documentation preview :books:: https://jupysql--120.org.readthedocs.build/en/120/

Connection str error

---

doc/environment.yml
doc/howto.md
setup.py

adds example to convert to polars
Closes #x
----
:books: Documentation preview :books:: https://jupysql--139.org.readthedocs.build/en/139/

adds example to convert to polars

---

CONTRIBUTING.md
doc/_toc.yml
doc/community/developer-guide.md
doc/environment.yml

Created a new section to describe how to write unit tests
Closes #x
----
:books: Documentation preview :books:: https://jupysql--163.org.readthedocs.build/en/163/

adds developer guide

---

doc/environment.yml
src/sql/connection.py
src/sql/magic.py
src/sql/plot.py
src/sql/run.py
src/tests/test_connection.py

Fix https://github.com/ploomber/jupysql/pull/171#issuecomment-1450947174
This should go to master
---------
Closes #x
----
:books: Documentation preview :books:: https://jupysql--189.org.readthedocs.build/en/189/

Add: test - error when there is no active connection - 156 to master

---

CHANGELOG.md
setup.py
src/sql/column_guesser.py
src/sql/connection.py
src/sql/magic.py
src/sql/parse.py
src/sql/plot.py
src/sql/run.py
src/tests/test_magic.py
src/tests/test_parse.py

Remove pin for prettytable version. Now supports the newest version of prettytable.
Closes #177 
----
:books: Documentation preview :books:: https://jupysql--191.org.readthedocs.build/en/191/

support prettytable 2.0

---

CHANGELOG.md
src/sql/command.py

Closes #x
----
:books: Documentation preview :books:: https://jupysql--193.org.readthedocs.build/en/193/

clearer error message

---

doc/integrations/duckdb.md

passed parameters into connections
Closes #174 
----
:books: Documentation preview :books:: https://jupysql--190.org.readthedocs.build/en/190/

improved duckdb integration doc

---

doc/_toc.yml
doc/integrations/polars.md

Closes #x
----
:books: Documentation preview :books:: https://jupysql--202.org.readthedocs.build/en/202/

adds polars tutorial

---

doc/api/configuration.md
doc/api/magic-plot.md
doc/api/magic-render.md
doc/api/magic-sql.md
doc/community/developer-guide.md
doc/compose.md
doc/connecting.md
doc/csv.md
doc/howto.md
doc/howto/json.md
doc/howto/postgres-connect.ipynb
doc/howto/syntax-highlighting.md
doc/integrations/duckdb.md
doc/integrations/mssql.ipynb
doc/integrations/mysql.ipynb
doc/integrations/pandas.md
doc/integrations/polars.md
doc/intro.md
doc/plot-legacy.md
doc/plot.md
doc/quick-start.md
doc/user-guide/tables-columns.md
doc/user-guide/template.md

Closes #x
----
:books: Documentation preview :books:: https://jupysql--207.org.readthedocs.build/en/207/

adds html metadata

---

doc/_toc.yml
doc/conf.py
doc/integrations/clickhouse.ipynb

Closes #x
----
:books: Documentation preview :books:: https://jupysql--209.org.readthedocs.build/en/209/

adds clickhouse tutorial

---

doc/api/configuration.md
doc/api/magic-plot.md
doc/api/magic-render.md
doc/api/magic-sql.md
doc/community/developer-guide.md
doc/compose.md
doc/conf.py
doc/connecting.md
doc/csv.md
doc/environment.yml
doc/howto.md
doc/howto/json.md
doc/howto/postgres-connect.ipynb
doc/howto/syntax-highlighting.md
doc/integrations/duckdb.md
doc/integrations/mariadb.ipynb
doc/integrations/mssql.ipynb
doc/integrations/mysql.ipynb
doc/integrations/pandas.md
doc/integrations/polars.md
doc/intro.md
doc/plot-legacy.md
doc/plot.md
doc/quick-start.md
doc/user-guide/tables-columns.md
doc/user-guide/template.md

Closes #x
----
:books: Documentation preview :books:: https://jupysql--211.org.readthedocs.build/en/211/

migration to jupyter book 0.14

---

.readthedocs.yml

Closes #x
----
:books: Documentation preview :books:: https://jupysql--212.org.readthedocs.build/en/212/

enabling htmlzip docs

---

CHANGELOG.md
doc/community/vs.md

Added summary section for jupysql vs ipython-sql
Closes #x
----
:books: Documentation preview :books:: https://jupysql--225.org.readthedocs.build/en/225/

jupysql vs ipython-sql

---

.github/workflows/ci.yaml
CHANGELOG.md
setup.py
src/sql/connection.py
src/sql/magic.py
tasks.py

Made changes to support SQL Alchemy 2.0. The changes were modeled after this https://github.com/catherinedevlin/ipython-sql/pull/225. The changes allow support for alchemy version 2.0 and older versions.
Second PR since the last one went bad. 
Closes #167 
----
:books: Documentation preview :books:: https://jupysql--219.org.readthedocs.build/en/219/

changes to support sqlalchemy 2.0

---

src/sql/command.py
src/sql/run.py
src/tests/test_magic.py

Closes #x
----
:books: Documentation preview :books:: https://jupysql--231.org.readthedocs.build/en/231/

adds test to check column names with dollar sign

---

src/sql/run.py
src/tests/integration/test_duckDB.py

Logger level = DEBUG
No Preset Logger Level
Closes #x
----
:books: Documentation preview :books:: https://jupysql--254.org.readthedocs.build/en/254/

Change print -> logger.debug

---

CHANGELOG.md
setup.py
src/sql/__init__.py

Closes #x
----
:books: Documentation preview :books:: https://jupysql--261.org.readthedocs.build/en/261/

pin sqlalchemy 1.x

---

setup.py
src/tests/conftest.py
src/tests/test_magic.py

Add test case to cover `--save` and `--with` query usage
Per [this request](https://github.com/ploomber/jupysql/issues/87#issuecomment-1437645060)
Closes #87
----
:books: Documentation preview :books:: https://jupysql--238.org.readthedocs.build/en/238/

Add Test Case - improvements to CTE feature

---

doc/user-guide/data-profiling.md
doc/user-guide/ggplot.md
doc/user-guide/template.md

Closes #x
----
:books: Documentation preview :books:: https://jupysql--299.org.readthedocs.build/en/299/

adds notes on unreleased features

---

src/sql/ggplot/aes.py
src/sql/ggplot/facet_wrap.py
src/sql/ggplot/geom/geom_boxplot.py
src/sql/ggplot/geom/geom_histogram.py
src/sql/ggplot/ggplot.py

Telemetry added to `ggplot` api
----
:books: Documentation preview :books:: https://jupysql--303.org.readthedocs.build/en/303/

ggoplot api telemetry

---

doc/api/magic-sql.md
doc/howto.md

Closes #311
----
:books: Documentation preview :books:: https://jupysql--315.org.readthedocs.build/en/315/

improves docs on connection alias

---

CONTRIBUTING.md
doc/compose.md

Introduced catchy intro, along with a summary of what JupySQL does in the example.
Closes https://github.com/ploomber/jupysql/issues/280
Preview https://jupysql--300.org.readthedocs.build/en/300/compose.html

CTE tutorial improvements

---

.github/workflows/ci-integration-db.yaml
doc/tutorials/etl.md
setup.py
src/sql/_testing.py
src/sql/ggplot/__init__.py
src/sql/ggplot/aes.py
src/sql/ggplot/facet_wrap.py
src/sql/ggplot/geom/__init__.py
src/sql/ggplot/geom/geom_boxplot.py
src/sql/ggplot/geom/geom_histogram.py
src/sql/ggplot/ggplot.py
src/sql/plot.py
src/tests/integration/conftest.py
src/tests/integration/test_containers.py
src/tests/integration/test_generic_db_opeations.py
src/tests/integration/test_mssql.py
src/tests/test_ggplot.py

Adds test for MSSQL intregration
Closes #197
----
:books: Documentation preview :books:: https://jupysql--320.org.readthedocs.build/en/320/

Adds support for MSSQL 

---

.github/workflows/changelog.yml
.github/workflows/chatops.yml

Adding two new workflows to see if they help us improve our development workflow
`chatops.yml`: post a comment saying `/format` to format the latest commit in the PR (will create a new commit and push it)
`changelog.yml`: a bot will post a message if the current PR hasn't modified the `CHANGELOG.md`
----
:books: Documentation preview :books:: https://jupysql--343.org.readthedocs.build/en/343/

adds two workflows

---

doc/api/configuration.md
doc/api/magic-plot.md
doc/api/magic-render.md
doc/compose.md
doc/connecting.md
doc/howto/autocompletion.md
doc/howto/csv.md
doc/howto/json.md
doc/howto/syntax-highlighting.md
doc/integrations/pandas.md
doc/integrations/polars.md
doc/intro.md
doc/plot-legacy.md
doc/plot.md
doc/quick-start.md
doc/tutorials/etl.md
doc/user-guide/interactive.md
doc/user-guide/tables-columns.md

Closes #314 
----
:books: Documentation preview :books:: https://jupysql--340.org.readthedocs.build/en/340/

Update md headers

---

CHANGELOG.md
doc/api/magic-render.md
doc/integrations/mariadb.ipynb
doc/integrations/mssql.ipynb
doc/integrations/mysql.ipynb
doc/integrations/postgres-connect.ipynb

Updated integration tutorials to showcase more JupySQL features.
----
:books: Documentation preview :books:: https://jupysql--356.org.readthedocs.build/en/356/

updates integration tutorials

---

.github/workflows/ci.yaml
setup.py

Closes #X
----
:books: Documentation preview :books:: https://jupysql--363.org.readthedocs.build/en/363/

disable parallel tests

---

src/sql/util.py
src/tests/test_util.py

Suggest user a missing `--with` argument
Closes #355 
----
:books: Documentation preview :books:: https://jupysql--361.org.readthedocs.build/en/361/

suggestion for stored query added

---

doc/user-guide/data-profiling.md
doc/user-guide/ggplot.md
doc/user-guide/interactive.md
doc/user-guide/template.md

Closes #X
----
:books: Documentation preview :books:: https://jupysql--364.org.readthedocs.build/en/364/

updates admonitions

---

doc/_toc.yml
doc/integrations/compatibility.md

Closes #374
----
:books: Documentation preview :books:: https://jupysql--378.org.readthedocs.build/en/378/

adds compat table

---

.github/workflows/ci-integration-db.yaml
src/sql/_testing.py
src/tests/integration/conftest.py
src/tests/integration/test_generic_db_operations.py
src/tests/integration/test_mssql.py

I changed the integration testing settings so we run them in the same way locally and in the CI. This will allow us to detect misconfigurations in the CI.
Also added some missing tests and did minor clean ups.
Closes #338
----
:books: Documentation preview :books:: https://jupysql--375.org.readthedocs.build/en/375/

Integration testing fix

---

CHANGELOG.md
doc/integrations/mariadb.ipynb
doc/integrations/mysql.ipynb
src/sql/inspect.py
src/tests/test_inspect.py

Closes #206
----
:books: Documentation preview :books:: https://jupysql--370.org.readthedocs.build/en/370/

fix `%sqlcmd tables/columns` in MySQL

---

doc/connecting.md
doc/integrations/mariadb.ipynb
doc/integrations/mssql.ipynb
doc/integrations/mysql.ipynb
doc/quick-start.md
doc/user-guide/FAQ.md

I made some improvements to the connecting.md tutorial:
- better section organization
- add more connection methods
- fixes inaccurate documentation (some examples were broken)
- make all snippets runnable to detect errors (so the point above doesn't happen again)
- moved notes to the relevant tutorials
Doc preview: https://jupysql--399.org.readthedocs.build/en/399/connecting.html

adds more methods for connecting to a db

---

.github/workflows/ci.yaml
doc/connecting.md
setup.py

Fixed polars version
Closes #313 
----
:books: Documentation preview :books:: https://jupysql--408.org.readthedocs.build/en/408/

Fix polars version

---

src/sql/run.py
src/tests/test_resultset.py

Added condition to check if `self.pretty is None` before adding rows.
Closes #476 
----
:books: Documentation preview :books:: https://jupysql--500.org.readthedocs.build/en/500/

Pretty table add_rows fix

---

doc/api/magic-sql.md

Fixed user guide on variable expansion
Closes 
----
:books: Documentation preview :books:: https://jupysql--496.org.readthedocs.build/en/496/

variable expansion fix

---

doc/_toc.yml
doc/tutorials/product-analytics.md

Tutorial on product analytics
Closes #264 
----
:books: Documentation preview :books:: https://jupysql--485.org.readthedocs.build/en/485/

Product analytics tutorial

---

doc/_toc.yml
doc/conf.py
doc/integrations/trinodb.ipynb

Added .ipynb notebook for Trino DB integration guide. Kept template similar to PostgreSQL guide, but due to different functionality in JupySQL, had to resort to some changes. For eg, `%sqlplot` magic command is not supporting `--schema` option, so specified schema in query itself. Other current issues include not being able to write entire pandas dataframe to Trino for which I have linked Trino's query length configuration properties documentation.
Closes #436 
----
:books: Documentation preview :books:: https://jupysql--516.org.readthedocs.build/en/516/

trinodb integration guide first review 

---

.github/workflows/ci-integration-db-live.yaml
.github/workflows/ci-integration-db.yaml
.github/workflows/ci.yaml

Add two integration testing (non-live, live) as the prerequisites jobs before running `release` job
[CI action result](https://github.com/ploomber/jupysql/actions/runs/5093457834)
Closes #514
----
:books: Documentation preview :books:: https://jupysql--520.org.readthedocs.build/en/520/

CD script not taking into account integration tests

---

.github/workflows/ci.yaml
doc/community/developer-guide.md
doc/compose.md
doc/howto.md
doc/howto/json.md
doc/integrations/duckdb.md
doc/plot.md
doc/tutorials/excel.md
doc/user-guide/data-profiling.md
doc/user-guide/interactive.md
doc/user-guide/tables-columns.md
pyproject.toml
src/sql/_testing.py
src/sql/command.py
src/sql/magic_cmd.py
src/sql/run.py
src/tests/integration/conftest.py
src/tests/integration/test_generic_db_operations.py
src/tests/integration/test_questDB.py
src/tests/test_magic.py

Closes #X
----
:books: Documentation preview :books:: https://jupysql--527.org.readthedocs.build/en/527/

adds `codespell`

---

.github/workflows/ci.yaml

Skip tests if only the doc has been modified
Closes #575
----
:books: Documentation preview :books:: https://jupysql--577.org.readthedocs.build/en/577/

Skip tests if only doc has been modified

---

.github/workflows/ci.yaml

Revert "Skip tests if only doc has been modified"

---

.github/workflows/ci-integration-db-live.yaml
.github/workflows/ci-integration-db.yaml

Add some documentation to CI workflow files
Closes #565 
----
:books: Documentation preview :books:: https://jupysql--585.org.readthedocs.build/en/585/

document integration test cloud vs local

---

.github/workflows/ci.yaml
.github/workflows/workflow-edits.yml

Added Changelog check to CI
Closes #X
----
:books: Documentation preview :books:: https://jupysql--608.org.readthedocs.build/en/608/

Changelog checking - CI

---

CHANGELOG.md
doc/api/magic-sql.md

Added Persist replace to API section
Closes #539
----
:books: Documentation preview :books:: https://jupysql--630.org.readthedocs.build/en/630/

persist replace in doc

---

doc/user-guide/py-scripts.md

Broken link in the docs fixed
Fixed by @neelasha23 in this [PR](https://github.com/ploomber/jupysql/pull/705/files#diff-dcc5816953c9f320a45589a4392c128ed4e7a939e2f15a84f49f526b27cfe7f8)
Closes #X
----
:books: Documentation preview :books:: https://jupysql--708.org.readthedocs.build/en/708/

The failing CI was fixed due to a broken link

---

doc/environment.lock.yml
doc/environment.yml
doc/howto/json.md
doc/integrations/duckdb-sqlalchemy.md
doc/user-guide/data-profiling.md

Fixes doc building.
- re-generated doc/environment.lock.yml - the old version was breaking due to an incompatible package
- added instructions at the top of dock/environment.yml on how to generate a new docl/environment.lock.yml
- fixed a tutorial due to an update in duckdb
- deleted some sections in the duckdb + sqlalchemy tutorial, there are some issues with duckdb-engine
- updated profiling tutorial not to use sqlite dbs since duckdb-engine gives errors
Closes #X
----
:books: Documentation preview :books:: https://jupysql--742.org.readthedocs.build/en/742/

fix doc building

---

CHANGELOG.md
doc/_toc.yml
doc/community/developer-guide.md
doc/integrations/duckdb-native.md
doc/integrations/duckdb.md
doc/tutorials/duckdb-native-sqlalchemy.md
noxfile.py
setup.py
src/sql/_testing.py
src/sql/connection/connection.py
src/sql/magic.py
src/sql/run/resultset.py
src/sql/run/run.py
src/sql/warnings.py
src/tests/integration/test_connection.py
src/tests/integration/test_duckDB.py
src/tests/integration/test_run.py
src/tests/test_connection.py
src/tests/test_magic.py
src/tests/test_resultset.py

from the changelog:
* [Fix] Fix bug that caused the query transpilation process to fail when passing multiple statements
* [Feature] Adds `with_` to `{SQLAlchemyConnection, DBAPIConnection}.raw_execute` to resolve CTEs
* [Fix] Fixes error when creating tables and querying them in the same cell when using DuckDB + SQLAlchemy (closes #674)
* [Fix] Using native methods to convert to data frames from DuckDB when using native connections and SQLAlchemy
internal changes (not in the changelog):
- updated developer documentation
- testing mssql with pytds
- moved the autocommit logic to connection.py
- added missing tests

duckdb fixes + other improvements

---

CHANGELOG.md
doc/api/configuration.md
doc/user-guide/template.md
src/sql/connection/connection.py
src/sql/magic.py
src/tests/test_magic.py

Closes #X
----
:books: Documentation preview :books:: https://jupysql--775.org.readthedocs.build/en/775/

renaming named parameters option

---

.github/workflows/ci-integration-db-live.yaml
CHANGELOG.md
noxfile.py
setup.py
src/sql/_testing.py
src/sql/plot.py
src/sql/stats.py
src/tests/integration/conftest.py
src/tests/integration/test_generic_db_operations.py
src/tests/integration/test_mssql.py
src/tests/integration/test_stats.py

I added some redshift integration tests. more to come
Closes #X
----
:books: Documentation preview :books:: https://jupysql--777.org.readthedocs.build/en/777/

add first redshift integration tests

---

CHANGELOG.md
doc/integrations/compatibility.md
doc/integrations/mssql.ipynb
src/sql/connection/__init__.py
src/sql/connection/connection.py
src/sql/run/resultset.py
src/tests/integration/test_generic_db_operations.py
src/tests/test_connection.py
src/tests/test_resultset.py

- cleaning up ResultSet
- fixes an edge case when using SQL server
- updates compatibility table
- adds missing integration tests for bar and pie plots
Closes #X
----
:books: Documentation preview :books:: https://jupysql--781.org.readthedocs.build/en/781/

result set clean up + fix mssql edge case

---

doc/integrations/redshift.ipynb
doc/integrations/snowflake.ipynb

Closes #X
----
:books: Documentation preview :books:: https://jupysql--792.org.readthedocs.build/en/792/

adds notes to redshift and snowflake tutorials on sqlalchemy version

---

CHANGELOG.md
src/sql/run/resultset.py
src/tests/test_resultset.py

Closes #790
----
:books: Documentation preview :books:: https://jupysql--793.org.readthedocs.build/en/793/

fix CTE converstion to dataframe

---

CHANGELOG.md
src/sql/run/resultset.py
src/tests/test_resultset.py

Closes #682
----
:books: Documentation preview :books:: https://jupysql--802.org.readthedocs.build/en/802/

add resultset footer to plain text representation

---

CHANGELOG.md
src/sql/connection/connection.py
src/sql/parse.py
src/tests/test_connection.py

Closes #X
----
:books: Documentation preview :books:: https://jupysql--817.org.readthedocs.build/en/817/

fixes error that was converted into print

---

CHANGELOG.md
doc/api/configuration.md
doc/api/magic-sql.md
doc/user-guide/connection-file.md
src/sql/magic.py
src/tests/conftest.py
src/tests/test_command.py
src/tests/test_config.py
src/tests/test_magic.py

* [API Change] `%config SqlMagic.dsn_filename` default value changed from `odbc.ini` to `~/.jupysql/connections.ini`
Closes #X
----
:books: Documentation preview :books:: https://jupysql--818.org.readthedocs.build/en/818/

changes dsn_filename default value

---

CHANGELOG.md
noxfile.py
setup.py
src/sql/_testing.py
src/tests/integration/conftest.py
src/tests/integration/test_clickhouse.py
src/tests/integration/test_generic_db_operations.py

Closes #X
----
:books: Documentation preview :books:: https://jupysql--810.org.readthedocs.build/en/810/

Clickhouse integrations

---

CHANGELOG.md
src/sql/connection/connection.py
src/sql/display.py
src/tests/test_config.py

Closes https://github.com/ploomber/jupysql/issues/828
----
:books: Documentation preview :books:: https://jupysql--832.org.readthedocs.build/en/832/

show warning if default connection fails to initialize

---

CHANGELOG.md
src/sql/magic.py
src/tests/test_config.py

Display a message instead of an error when `toml` isn't installed and `pyproject.toml` is found 
Closes #825 
----
:books: Documentation preview :books:: https://jupysql--831.org.readthedocs.build/en/831/

make toml optional

---

CHANGELOG.md
doc/_toc.yml
doc/howto/db-drivers.md
src/sql/_testing.py
src/sql/connection/connection.py
src/sql/connection/error_handling.py
src/tests/test_connection.py
src/tests/test_magic.py

- improved the error messages when a connection fails to initialize
- also updated `_testing.py` to make it simpler to start a single container (instead of all of them)
Closes #X
----
:books: Documentation preview :books:: https://jupysql--833.org.readthedocs.build/en/833/

clearer error messages if a connection fails to initialize

---

CHANGELOG.md
src/sql/command.py
src/tests/test_magic.py

Fix error when a linebreak is included during nonidentifier validation process
Closes #X
----
:books: Documentation preview :books:: https://jupysql--835.org.readthedocs.build/en/835/

test doc build

---

CHANGELOG.md
src/sql/display.py
src/sql/magic.py
src/sql/util.py
src/tests/test_config.py

Closes #771 
Acceptance criteria:
1. if pyproject.toml is defined but there is no [tool.jupysql] section, then display a link to the docs so users know how to use it
2. if [tool.jupysql] exists but it's empty, then mention that the section is empty and display a link to the docs
----
:books: Documentation preview :books:: https://jupysql--823.org.readthedocs.build/en/823/

improve pyproject.toml load message

---

src/sql/magic_plot.py
src/sql/parse.py
src/tests/test_magic_plot.py

Closes #595 
----
:books: Documentation preview :books:: https://jupysql--839.org.readthedocs.build/en/839/

Remove nargs from plotting

---

CHANGELOG.md
doc/_toc.yml
doc/environment.lock.yml
doc/environment.yml
doc/integrations/chdb.md

Closes https://github.com/chdb-io/chdb/issues/15
----
:books: Documentation preview :books:: https://jupysql--857.org.readthedocs.build/en/857/

Add chDB integration  doc

---

CHANGELOG.md
doc/api/configuration.md
doc/user-guide/connection-file.md

Clarify the use of `pyproject.toml` and `connections.ini` in documentations
Closes #850 
----
:books: Documentation preview :books:: https://jupysql--858.org.readthedocs.build/en/858/

clarify pyproject.toml and connections.ini

---

doc/conf.py
pyproject.toml

Closes #X
----
:books: Documentation preview :books:: https://jupysql--862.org.readthedocs.build/en/862/

adds cloud link

---

doc/integrations/chdb.md
src/sql/command.py

Unused var in Line 122 `_var_expand` function in `src/sql/command.py`
Closes #864 
----
:books: Documentation preview :books:: https://jupysql--865.org.readthedocs.build/en/865/

removed unused var

---

doc/api/configuration.md
doc/integrations/chdb.md

Added documentation for options missing from the configuration docs (`autocommit`, `column_local_vars`, `short_errors`)
Reorganized code and documentation for uniformity
Closes #691 
----
:books: Documentation preview :books:: https://jupysql--867.org.readthedocs.build/en/867/

Added documentation for options that were missing from %sql Configuration

---

CHANGELOG.md
doc/api/magic-plot.md
doc/api/magic-sql.md
doc/howto/json.md
doc/plot.md
doc/quick-start.md
doc/tutorials/product-analytics.md
doc/user-guide/template.md

Update documentation to use `string.Template` and remove `--with` since it's optional
Closes #838 
----
:books: Documentation preview :books:: https://jupysql--871.org.readthedocs.build/en/871/

update outdated documentation

---

CHANGELOG.md
src/sql/connection/connection.py
src/tests/test_magic.py

Fix error when trying to access previously non-existing file
Closes #840 
----
:books: Documentation preview :books:: https://jupysql--873.org.readthedocs.build/en/873/

Invalid input error

---

setup.py
src/tests/integration/test_generic_db_operations.py

Unable to reproduce errors
Removed pytest xfail for the integration test to check if integration is successful
Closes #812 
----
:books: Documentation preview :books:: https://jupysql--885.org.readthedocs.build/en/885/

Fixed Clickhouse issue in CTE 

---

src/tests/integration/test_clickhouse.py

Removed `xfail` on test `test_sqlplot_histogram`.
Closes #811 
----
:books: Documentation preview :books:: https://jupysql--915.org.readthedocs.build/en/915/

Clickhouse integration test fix for issue#811

---

src/sql/plot.py

Using axes if passed as parameter to boxplot function
Closes #923 
----
:books: Documentation preview :books:: https://jupysql--924.org.readthedocs.build/en/924/

boxplot ax

---

CHANGELOG.md
doc/api/python.rst
examples/run_statements.py
src/sql/run/run.py
src/tests/integration/test_generic_db_operations.py

Added `run_statements` from `sql.run.run`
Closes #922 
----
:books: Documentation preview :books:: https://jupysql--929.org.readthedocs.build/en/929/

Python api docs

---

src/tests/integration/test_generic_db_operations.py

Closes #925 
----
:books: Documentation preview :books:: https://jupysql--928.org.readthedocs.build/en/928/

snowflake and redshift tests fix

---

src/sql/error_handler.py
src/sql/util.py
src/tests/integration/test_generic_db_operations.py

Handling DB specific errors for Snowflake and Clickhouse
Closes #931 #932 
----
:books: Documentation preview :books:: https://jupysql--933.org.readthedocs.build/en/933/

Db specific errors

---

CHANGELOG.md
src/sql/run/resultset.py
src/tests/test_magic.py
src/tests/test_resultset.py

Closes https://github.com/ploomber/sql/issues/106 https://github.com/ploomber/sql/issues/107
----
:books: Documentation preview :books:: https://jupysql--937.org.readthedocs.build/en/937/

Raising driver errors in resultset

---

CHANGELOG.md
doc/integrations/oracle.ipynb
src/sql/_testing.py

Hi all,
This PR is a minor change upgrading the Oracle Database docker image from [gvenzl/oracle-xe](https://hub.docker.com/r/gvenzl/oracle-xe) to the successor image [gvenzl/oracle-free](https://hub.docker.com/r/gvenzl/oracle-free).
N/A
----
:books: Documentation preview :books:: https://jupysql--943.org.readthedocs.build/en/943/

Upgrade to Oracle Database Free

---

doc/jupyterlab/sharing.md
setup.py

Closes #X
----
:books: Documentation preview :books:: https://jupysql--961.org.readthedocs.build/en/961/

Sqlglot version pinned

---

doc/jupyterlab/format-sql.ipynb

Closes #X
----
📚 Documentation preview 📚: https://jupysql--978.org.readthedocs.build/en/978/

Remove Binder links

---

doc/community/developer-guide.md

- Add section in `doc/community/developer-guide.md` to document the fix for Snowflake error: `No active warehouse selected in the current session. Select an active warehouse with the 'use warehouse' command.`
- I can also move the section to `doc/integration/snowflake.md` but felt that this was more developer oriented so left it in the developer guide
Closes #X
----
📚 Documentation preview 📚: https://jupysql--981.org.readthedocs.build/en/981/

Document Snowflake Warehouse Fix

---

doc/conf.py

Change banner content
Closes #
----
📚 Documentation preview 📚: https://jupysql--988.org.readthedocs.build/en/988/

Banner changed

---

CHANGELOG.md
setup.py
src/tests/test_magic.py

Closes #X
----
📚 Documentation preview 📚: https://jupysql--990.org.readthedocs.build/en/990/

updates dependencies

---

CHANGELOG.md
setup.py

Closes #X
----
📚 Documentation preview 📚: https://jupysql--1018.org.readthedocs.build/en/1018/

revert changelog
