doc/connecting.md, src/sql/command.py, src/sql/connection.py, src/sql/magic.py, src/sql/parse.py, src/tests/conftest.py, src/tests/test_command.py, src/tests/test_magic.py, src/tests/test_parse.py
Closes #16
I also added more unit tests and created `SQLCommand` to encapsulate the input parsing logic (which allows us to test it more easily)
=> allow to pass existing `sqlalchemy.engine.Engine`

src/sql/command.py, src/sql/magic.py, src/tests/test_command.py
issue https://github.com/ploomber/jupysql/issues/32 has been closed already but I'm opening this PR anyway since it adds an explicit test + moves the parsing logic to SQLCommand which is our abstraction to test the parsing logic without calling the magic.
=> Var substitution

doc/howto.md
closes #49
Registering SQLite UDFs is possible since version 0.5.1 when we added support for registering existing SQLAlchemy engines; this PR adds an example.
=> adds example

setup.py
Fixed SQLAlchemy version.
SQLAlchemy 2 is still in beta and the following libraries are incompatible with it:
1. ipython-sql
2. duckdb_engine
Issue : #24
=> Not compatible with SQLAlchemy 2

doc/connecting.md, doc/howto.md, src/sql/connection.py, src/tests/conftest.py, src/tests/test_command.py, src/tests/test_connection.py, src/tests/test_magic.py
addressed a bunch of the currently opened issues. most of them are already solved so I just added tests. Also added some missing tests, and documented a few things. Commit messages contain descriptive names of what I did on each one.
**Important:** do not squash this PR, let's get all commits into the master branch since each commit contains useful messages.
=> closing a bunch of issues 

doc/api.md, doc/configuration.md, doc/howto.md, doc/quick-start.md, src/sql/command.py, src/sql/connection.py, src/sql/magic.py, src/tests/test_command.py, src/tests/test_connection.py, src/tests/test_magic.py, src/tests/test_parse.py
Closes https://github.com/ploomber/jupysql/issues/37
This PR adds a new option to the magics to allow connections to have an alias:
```
%sql {connection-string} --alias my-db
```
This allows users to close the connection with the alias:
```
%sql my-db --close
```
It also adds a few improvements to the docs.
=> Connection names

doc/_config.yml
Adding google analytics
I created a new property on our analytics console and then a new web stream. Is this the right approach?
Also, when creating the web stream, the form asked me for the URL. Will this break once we switch the docs from the readthedocs.org domain to our domain? If so, we'll have to remember this.
=> adds g analytics id

.github/workflows/ci.yaml, src/sql/magic.py, src/sql/run.py, src/sql/telemetry.py
we were missing running flake8 in the CI, I also ran `black` so flake8 passes
----
:books: Documentation preview :books:: https://jupysql--94.org.readthedocs.build/en/94/
=> running flake8 in the CI

doc/_toc.yml, doc/community/coc.md, doc/community/community.md, doc/community/support.md
Context:
Respond to https://github.com/ploomber/jupysql/issues/72 
We need to add a doc to explain user about our telemetry part. Since we are using the shared telemetry module, we may refer to the detail section of [User Statistics](https://docs.ploomber.io/en/latest/community/user-stats.html)
However, something we can do:
1. Add the support page under community in jupysql doc, which contains the Support + Telemetry section
2. Polish original [User Statistics](https://docs.ploomber.io/en/latest/community/user-stats.html) doc in the ploomber project, I've raised [the PR](https://github.com/ploomber/jupysql/pull/101) for patching
Changes in this PR:
- Add support doc
- Add coc doc
- Remove community doc (replaced by new coc doc and new support doc)
- Reorder the _toc ordering (Page …
=> Doc - Telemetry doc - Add more details on what's collected

CHANGELOG.md, src/sql/inspect.py, src/sql/magic.py, src/sql/magic_plot.py, src/sql/plot.py, src/sql/store.py, src/tests/test_inspect.py, src/tests/test_magic.py, src/tests/test_magic_plot.py, src/tests/test_plot.py, src/tests/test_store.py
Close https://github.com/ploomber/jupysql/issues/30
- Add @modify_exceptions decorator to function which might raise `ValueError`, `TypeError` exception, to show the community link
- Patch some test cases
- Change all places `ValueError` -> `PloomberValueError`
- Change existing test cases to cover `PloomberValueError`
- Add new test cases to cover `PloomberValueError`
- Add CHANGELOG as
* `[Fix] Shows the community link to the exception message of ValueError and TypeError` in 0.5.4dev
Example for the `PloomberValueError` message
----
:books: Documentation preview :books:: https://jupysql--106.org.readthedocs.build/en/106/
=> Updating jupysql error messages - ValueError, TypeError

CHANGELOG.md, doc/connecting.md
Close https://github.com/ploomber/jupysql/issues/109
- Fix Typo `PosgreSQL` -> `PostgreSQL`
Before:
After:
----
:books: Documentation preview :books:: https://jupysql--110.org.readthedocs.build/en/110/
=> Fix: Doc Typo in Connecting: PostgreSQL

CHANGELOG.md, doc/howto.md, src/sql/magic.py, src/tests/test_magic.py
closes #102
----
:books: Documentation preview :books:: https://jupysql--112.org.readthedocs.build/en/112/
=> adding `%jupysql`/`%%jupysql` as alias

CHANGELOG.md, src/sql/connection.py, src/tests/test_connection.py, src/tests/test_magic.py
* Provide the suggestion message when the driver package is not found
- Correct driver name, but not install in the user environment
- Closely matching to correct driver name, but not quite correct
- Neither the above cases and incorrect driver name
* Test cases to cover those 
Correct driver name `pymysql`, no `pymysql` package installed
1. 
```
%sql mysql+pymysql://database_url
```
2.
```
UsageError: No module named 'pymysql'
To fix it, try to install package: pymysql
For technical support: https://ploomber.io/community
Documentation: https://jupysql.ploomber.io/en/latest/connecting.html
```
1. 
```
%sql mysql+pymysqll://
```
2.
```
UsageError: Can't load plugin: sqlalchemy.dialects:mysql.pymysqll
To fix it, perhaps you meant to use driver name: pymysql
For technical support: …
```
=> Fix: detecting when a db driver is missing

CHANGELOG.md, doc/api/configuration.md, setup.py, src/sql/magic.py, src/sql/run.py, src/tests/test_magic.py
Allows auto conversation of sql cells to polars Dataframes.
Closes #138
----
:books: Documentation preview :books:: https://jupysql--142.org.readthedocs.build/en/142/
=> Support for SqlMagic.autopolars

doc/environment.yml, src/sql/connection.py, src/sql/magic.py, src/sql/plot.py, src/sql/run.py, src/tests/test_connection.py
Add test case to cover 
```
AttributeError: 'NoneType' object has no attribute '_get_curr_connection_info'
```
[Closes #156](https://github.com/ploomber/jupysql/issues/156)
----
:books: Documentation preview :books:: https://jupysql--171.org.readthedocs.build/en/171/
=> Add: test - error when there is no active connection

CHANGELOG.md, src/sql/command.py, src/tests/integration/test_generic_db_opeations.py, src/tests/test_command.py
Fix the bug - deprecation warning incorrectly displayed
Originally, we have the custom variable substitution, but it will also handle the connection string like this, which we have the regex to detect if it's contains `:variable`, it will detect connection string as variable substitution case.
Connection string:
`mysql+mysqldb://user:password@127.0.0.1:3306/db`
(`:password` was treat as variable)
Fix by executing the `_var_expand` after the command is parsed by `parse.parse()`, so it would not contain connecting string anymore
Closes #203 
----
:books: Documentation preview :books:: https://jupysql--213.org.readthedocs.build/en/213/
=> Fix Incident - deprecation warning incorrectly displayed

src/sql/command.py, src/tests/test_command.py
The root cause is originally we only rely on `has_SQLAlchemy_var_expand = ":" in sql` to see if the user might use sqlalchemy variable expansion
Fix by more delicate way - check the query statement it contains variable from `user_ns`
Closes #214
----
:books: Documentation preview :books:: https://jupysql--215.org.readthedocs.build/en/215/
=> Fix - Issue better detect the user uses sqlalchemy variable expansion

doc/integrations/duckdb.md
Added a "Listing Tables" and "Listing Columns" section at the bottom of the file. These sections demonstrate the steps needed to listing tables or columns from .csv and .parquet files. 
I wasn't sure if this addition should have been included in the change log or not. Please let me know what you think and I'd be happy to make any necessary changes.
Closes #221 
----
:books: Documentation preview :books:: https://jupysql--227.org.readthedocs.build/en/227/
=> updated to include listing tables & columns

pyproject.toml
check-for-broken-links sometimes fails on "binder.ploomber.io".
"binder.ploomber.io" added to `ignore_substrings` in pyproject.toml
No issue
----
:books: Documentation preview :books:: https://jupysql--252.org.readthedocs.build/en/252/
=> Ignore "binder.ploomber.io" on check-for-broken-links

src/sql/run.py, src/tests/test_run.py
Refactored run function and added unit test coverage. 
Addressed comments from #233
Closes #161
----
:books: Documentation preview :books:: https://jupysql--267.org.readthedocs.build/en/267/
=> Refactor run function and added unit test coverage

CHANGELOG.md, README.md, doc/quick-start.md
hey @sterlinm. can I add your GitHub handle to our changelog and quickstart? we want to highlight your contribution
@idomic: @sterlinm is maintaining a [conda-forge](https://github.com/conda-forge/jupysql-feedstock/pull/1) recipe so jupysql can be installed via `conda install` 🎉
----
:books: Documentation preview :books:: https://jupysql--376.org.readthedocs.build/en/376/
=> adds conda install command to quickstart

examples/plot_boxplot.py, examples/plot_boxplot_custom.py, examples/plot_boxplot_horizontal.py, examples/plot_boxplot_many.py, examples/plot_histogram.py, examples/plot_histogram_many.py, src/sql/connection.py, src/sql/magic.py, src/sql/plot.py, src/sql/run.py, src/sql/store.py, src/sql/util.py, src/tests/test_connection.py, src/tests/test_plot.py, src/tests/test_store.py, src/tests/test_telemetry.py
Fix design problem - #386 
Since some methos in Connection Class has same problem, I also fix those
Make those methos as non-class method:
```
- _get_curr_sqlalchemy_connection_info
- _get_curr_sqlglot_dialect
- is_use_backtick_template
- _transpile_query
- get_curr_identifiers
- _transpile_query
```
Closes https://github.com/ploomber/jupysql/issues/386
----
:books: Documentation preview :books:: https://jupysql--389.org.readthedocs.build/en/389/
=> transpile query not classmethod

CHANGELOG.md, doc/_toc.yml, doc/integrations/mindsdb.ipynb, doc/integrations/mssql.ipynb, doc/integrations/postgres-connect.ipynb, doc/user-guide/tables-columns.md, doc/user-guide/testing-columns.md, src/sql/magic_cmd.py, src/tests/integration/test_generic_db_operations.py, src/tests/test_magic_cmd.py
Improving user experience for %sqlcmd, more specific errors
Closes #275 
----
:books: Documentation preview :books:: https://jupysql--341.org.readthedocs.build/en/341/
=> %sqlcmd improvements

doc/integrations/questdb.ipynb
JupySQL was incorrectly shown as JuppySQL with double 'p'. Fixed
----
:books: Documentation preview :books:: https://jupysql--454.org.readthedocs.build/en/454/
=> [Doc] Typo on JupySQL

CHANGELOG.md, src/sql/command.py, src/sql/connection.py, src/tests/test_magic.py
Fixed a bug when using existing engine objects and passing `--alias`
Closes #X
----
:books: Documentation preview :books:: https://jupysql--446.org.readthedocs.build/en/446/
=> fixes --alias when passing an existing engine

CHANGELOG.md, doc/api/configuration.md, doc/community/vs.md, src/sql/magic.py, src/sql/run.py, src/tests/test_magic.py
- Change default display limit as -> `10`
- Add unlimited display limit support if user sets value as `0` or `None`
Case 1: Unset -> Default display limit as  10 (Unset)
https://user-images.githubusercontent.com/123580782/235429111-4233f783-16f9-4cda-a8ec-9beb88ac274b.mov
Case 2: Set as 20
Case 3: Set as None (no limit)
[Doc preview](https://jupysql--462.org.readthedocs.build/en/462/api/configuration.html#displaylimit)
Closes https://github.com/ploomber/jupysql/issues/419
----
:books: Documentation preview :books:: https://jupysql--462.org.readthedocs.build/en/462/
=> Change default displaylimit value

CHANGELOG.md, doc/community/developer-guide.md, src/sql/__init__.py, src/sql/connection.py, src/sql/error_message.py, src/sql/magic.py, src/tests/conftest.py, src/tests/integration/conftest.py, src/tests/integration/test_postgreSQL.py, src/tests/test_magic.py, src/tests/test_syntax_errors.py
Overriding sqlalchemy error handling for the case:
1. Syntax errors in query (we are using sqlglot to parse the query and prompt possible errors/ suggestions).
2. Password not provided/ in-accessible for postgres connections
3. Incorrect URL connection string for DuckDB
Closes #229 
----
:books: Documentation preview :books:: https://jupysql--400.org.readthedocs.build/en/400/
=> SQLachemy error overriding

CHANGELOG.md, doc/intro.md, src/sql/command.py, src/sql/magic.py, src/sql/parse.py, src/tests/test_command.py, src/tests/test_magic.py, src/tests/test_parse.py
Easily capture and print result variables at the same time using new `= <<` syntax.
Closes #418 
----
:books: Documentation preview :books:: https://jupysql--501.org.readthedocs.build/en/501/
=> Syntactic sugar for outputting result variables

CHANGELOG.md, src/sql/connection.py, src/tests/test_connection.py
Added PEP 249 compliance to custom connection. 
Checking whether the connection object has `close`, `commit` and `rollback` methods
Closes #433 
----
:books: Documentation preview :books:: https://jupysql--517.org.readthedocs.build/en/517/
=> checking custom connections according to PEP 249

.github/workflows/ci-integration-db.yaml, src/tests/integration/test_generic_db_operations.py, src/tests/integration/test_oracle.py
- Fix by adding the pipeline symbol | on the run attribute
Ref: https://stackoverflow.com/questions/56726429/how-to-run-multiple-commands-in-one-github-actions-docker
- Add `test_sqlplot_boxplot` in `src/tests/integration/test_oracle.py`, although it's known failing test case
Takes 7m+ to run the test:
Closes #514
----
:books: Documentation preview :books:: https://jupysql--535.org.readthedocs.build/en/535/
=> Fix CI integration local issue

CHANGELOG.md, doc/user-guide/template.md
Added more details in the parametrization tutorial
Closes #288 
----
:books: Documentation preview :books:: https://jupysql--570.org.readthedocs.build/en/570/
=> parametrization tutorial updates

CHANGELOG.md, doc/_toc.yml, doc/conf.py, doc/integrations/snowflake.ipynb
Snowflake integration guide
Closes #384 
----
:books: Documentation preview :books:: https://jupysql--591.org.readthedocs.build/en/591/
=> Snowflake guide

CHANGELOG.md, doc/api/configuration.md, src/sql/magic.py, src/sql/run.py, src/tests/test_magic.py
Modified the ResultSet Class to handle the styling applied to the result table.  Implemented the`set_style` method of `PrettyTable` to apply styling. Now we can apply all the styles supported by `PrettyTable` 
eg:  DEFAULT, MSWORD_FRIENDLY, PLAIN_COLUMNS, RANDOM, SINGLE_BORDER, DOUBLE_BORDER, MARKDOWN
Closes #54 
----
:books: Documentation preview :books:: https://jupysql--620.org.readthedocs.build/en/620/
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204812529638430
=> pretty table styling fix

.github/workflows/ci-integration-db-live.yaml, .github/workflows/ci-integration-db.yaml, .github/workflows/ci.yaml
Uploading failed test images
Closes #543 
----
:books: Documentation preview :books:: https://jupysql--607.org.readthedocs.build/en/607/
=> Upload test artifacts

CHANGELOG.md, doc/api/magic-plot.md, doc/api/magic-profile.md, doc/api/magic-render.md, doc/api/magic-sql.md, doc/quick-start.md
Added `%magic` to docs and APIs
Closes #97 
----
:books: Documentation preview :books:: https://jupysql--625.org.readthedocs.build/en/625/
=> Added `%magic?` to docs

CHANGELOG.md, src/tests/test_magic.py
Changed the test expected result to the updated duckdb output
Closes #631 
----
:books: Documentation preview :books:: https://jupysql--633.org.readthedocs.build/en/633/
=> 631 ci fix

.github/workflows/ci.yaml
Correct Syntax: `-e doc CHANGELOG.md`
Closes #661 
----
:books: Documentation preview :books:: https://jupysql--668.org.readthedocs.build/en/668/
=> Fixed CI (Doc checking)

CHANGELOG.md, src/sql/store.py, src/tests/test_magic_cte.py
Remove `WITH` when rendering a snippet when the snippet does not have a dependency
Closes #657 
----
:books: Documentation preview :books:: https://jupysql--673.org.readthedocs.build/en/673/
=> removing `with` when no dependency

CHANGELOG.md, src/sql/run.py, src/tests/test_resultset.py
Adding description after html representation of `ResultSet` and error message for AttributeError when invalid operation is performed
Closes #468 
----
:books: Documentation preview :books:: https://jupysql--655.org.readthedocs.build/en/655/
=> Resultset distinguishable

src/tests/conftest.py
Fixed an issue that caused errors when running unit tests.
Closes #X
----
:books: Documentation preview :books:: https://jupysql--696.org.readthedocs.build/en/696/
=> fix "too many open files" when running tests

CHANGELOG.md, src/sql/cmd/snippets.py, src/tests/test_magic_cmd.py
Change `%sqlcmd snippets` output into displaying 1. snippet name 2. snippet query 3. snippet table. 
Still working on 1. figuring out how to retrieve `SqlMagic.displaylimit` 2. adding test functions 3. update documentation if needed, but I want to know whether it's on the right direction or not.
Closes #648 
----
:books: Documentation preview :books:: https://jupysql--716.org.readthedocs.build/en/716/
=> snippets display improvement

CHANGELOG.md, doc/compose.md, doc/plot.md, src/sql/__init__.py, src/sql/command.py, src/sql/error_message.py, src/sql/magic.py, src/sql/magic_plot.py, src/sql/util.py, src/tests/integration/test_generic_db_operations.py, src/tests/test_command.py, src/tests/test_magic.py, src/tests/test_magic_cte.py, src/tests/test_magic_plot.py, src/tests/test_syntax_errors.py
Adding `--with` again 
Closes #684 
----
:books: Documentation preview :books:: https://jupysql--705.org.readthedocs.build/en/705/
=> Adding `--with` for CTE

.github/workflows/ci-integration-db-live.yaml, .github/workflows/ci-integration-db.yaml, .github/workflows/ci.yaml
This PR speeds up the CI, it was slowing down a lot because of a problem in ploomber-core
you can see it here:
before: https://github.com/ploomber/jupysql/actions/runs/5546740202/jobs/10127439854
after: https://github.com/ploomber/jupysql/actions/runs/5558949460/jobs/10154574710
i.e., Python 3.11 ubuntu went from 25mins to 6.5 mins! (on windows the performance increased even more)
(opened https://github.com/ploomber/core/issues/70 to investigate the root cause)
Closes #X
----
:books: Documentation preview :books:: https://jupysql--734.org.readthedocs.build/en/734/
=> fix CI speed

CHANGELOG.md, src/sql/connection.py, src/sql/magic.py, src/sql/plot.py, src/sql/run.py, src/sql/util.py
Replaced all the prints to display module
Closes #548
----
:books: Documentation preview :books:: https://jupysql--735.org.readthedocs.build/en/735/
=> Migrate user feedback to use display module

CHANGELOG.md, doc/api/configuration.md, doc/howto.md, environment.integration.yml, src/sql/connection.py, src/sql/error_message.py, src/sql/magic.py, src/sql/run.py, src/tests/conftest.py, src/tests/integration/conftest.py, src/tests/integration/test_duckDB.py, src/tests/integration/test_generic_db_operations.py, src/tests/test_magic.py, src/tests/test_magic_cte.py
- Fixed a problem that turned exceptions into print statements
- Because of the point above, some tutorials started failing, so I fixed them
- because of the first point, some integration tests started failing (they were failing from the beginning but fixing the error surfaced the problem), fixed some of them but marked others as xfail as it isn't clear what the purpose of those tests is (https://github.com/ploomber/jupysql/issues/749)
- added an environment.integration.yml to install dependencies for integration tests
- fixed an error in the integration tests that prevented running `DROP TABLE` in SQLite due to open cursor
Closes #X
----
:books: Documentation preview :books:: https://jupysql--746.org.readthedocs.build/en/746/
=> fixed error that was turned into print statement

CHANGELOG.md, doc/community/developer-guide.md, setup.py, src/sql/_testing.py, src/sql/cmd/test.py, src/sql/command.py, src/sql/connection/connection.py, src/sql/exceptions.py, src/sql/magic.py, src/sql/run/pgspecial.py, src/sql/store.py, src/tests/conftest.py, src/tests/integration/conftest.py, src/tests/integration/test_generic_db_operations.py, src/tests/integration/test_mssql.py, src/tests/integration/test_postgreSQL.py, src/tests/integration/test_questDB.py, src/tests/test_inspect.py, src/tests/test_magic.py, src/tests/test_magic_cmd.py, src/tests/test_magic_plot.py, src/tests/test_store.py, src/tests/test_util.py
I improved the fixture that creates the IPython session and fixed some bugs along the way. (also, I deleted some outdated sections in the developer documentation)
Change: calling `run_cell` now automatically raises exceptions, if any:
```python
ip.run_cell("%sql select * from some_unknown_table")
```
Why?
In many of our tests, we create an IPython session and run stuff like this:
```python
ip.run_cell("%sql select * from some_table")
```
The caveat is that `ip.run_cell` won't raise any exceptions automatically, so we had to add this pattern over and over again to ensure there were no issues:
```python
result = ip.run_cell("%sql select * from some_table")
assert result.error_in_exec is None
```
However, many tests require several calls:
```python
ip.run_cell("%sql select * from …
```
=> `ip.run_cell` now raises exceptions immediately

CHANGELOG.md, doc/api/configuration.md, doc/user-guide/template.md, src/sql/_testing.py, src/sql/connection/connection.py, src/sql/exceptions.py, src/sql/magic.py, src/sql/parse.py, src/sql/run/run.py, src/sql/warnings.py, src/tests/conftest.py, src/tests/test_magic.py, src/tests/test_parse.py, src/tests/test_testing.py
also fixing flake8 lint issues since version 6.1.0 added new rules
Closes #671
----
:books: Documentation preview :books:: https://jupysql--770.org.readthedocs.build/en/770/
=> adds `:variable` parameter substitution

.gitignore, CHANGELOG.md, benchmarks/profiling.py, doc/tutorials/duckdb-native-sqlalchemy.md, src/sql/run/resultset.py, src/sql/run/run.py
I noticed that we were making a call using sqlalchemy to retrieve the column names, we don't actually need that. Removing it improved performance.
Closes #X
----
:books: Documentation preview :books:: https://jupysql--780.org.readthedocs.build/en/780/
=> improves DuckDB performance when converting to pandas

CHANGELOG.md, src/sql/magic.py, src/tests/conftest.py, src/tests/integration/conftest.py, src/tests/test_magic.py
closes #753
----
:books: Documentation preview :books:: https://jupysql--795.org.readthedocs.build/en/795/
=>  do not expand ctes when the user supplies a cte 

CHANGELOG.md, doc/api/configuration.md, src/sql/__init__.py, src/sql/_current.py, src/sql/connection/connection.py, src/sql/exceptions.py, src/sql/magic.py, src/sql/run/resultset.py, src/sql/run/run.py, src/sql/warnings.py, src/tests/conftest.py, src/tests/integration/conftest.py, src/tests/test_column_guesser.py, src/tests/test_connection.py, src/tests/test_magic.py, src/tests/test_magic_display.py, src/tests/test_resultset.py
* [Fix] Perform `ROLLBACK` when SQLAlchemy raises `PendingRollbackError`
* [Fix] Perform `ROLLBACK` when `psycopg2` raises `current transaction is aborted, commands ignored until end of transaction block`
* [Fix] Perform `ROLLBACK` when `psycopg2` raises `server closed the connection unexpectedly` (closes #677)
* [Fix] Shorter `displaylimit` footer
* [API Change] `%config SqlMagic.feedback` now takes values `0` (disabled), `1` (normal), `2` (verbose)
* [Fix] `ResultSet` footer only displayed when `feedback=2`
* [Fix] Current connection and switching connections message only displayed when `feedback>=1`
* [Fix] `--persist/--persist-replace` perform `ROLLBACK` automatically when needed
----
:books: Documentation preview :books:: https://jupysql--798.org.readthedocs.build/en/798/
=> improves postgres compatibility + more granular feedback config

.gitignore, CHANGELOG.md, doc/_toc.yml, doc/api/configuration.md, doc/api/magic-sql.md, doc/community/vs.md, doc/user-guide/connection-file.md, src/sql/connection/connection.py, src/sql/exceptions.py, src/sql/magic.py, src/sql/parse.py, src/tests/test_magic.py, src/tests/test_parse.py
* [API Change] When loading connections from a `.ini` file via `%sql --section section_name`, the section name is set as the connection alias
* [API Change] Starting connections from a `.ini` file via `%sql [section_name]` has been deprecated
Also:
* Added missing documentation about reading `.ini` files
* Added missing unit tests
Closes #X
----
:books: Documentation preview :books:: https://jupysql--803.org.readthedocs.build/en/803/
=> loading from `.ini` files API changes

CHANGELOG.md, src/sql/run/resultset.py, src/tests/test_magic.py
Running a count statement with `displaylimit=None` or `displaylimit=0` now displays the result
Closes #801 
- [] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
----
:books: Documentation preview :books:: https://jupysql--815.org.readthedocs.build/en/815/
=> fix count statement when displaylimit=None

CHANGELOG.md, src/sql/command.py, src/sql/magic.py, src/sql/util.py, src/tests/test_magic.py
When a connection is pass through dictionary, list, or object, it raises an error with a more detailed message.
For instance, when `%sql some_list[0]` is passed to connect, it raises the following error.
```
UsageError: 'some_list[0]' is not a valid connection identifier. Please pass the variable's name directly, as passing object attributes, dictionaries or lists won't work.
```
Closes #764 
----
:books: Documentation preview :books:: https://jupysql--821.org.readthedocs.build/en/821/
=> error when passing a non-identifier to connect

CHANGELOG.md, src/sql/cmd/explore.py, src/sql/cmd/test.py, src/sql/inspect.py, src/sql/widgets/table_widget/table_widget.py, src/tests/test_magic_cmd.py
Add `--schema/-s` for `%sqlcmd` commands that support `--table/-t` and ensure `--table schema.table` works. This includes `columns`, `explore`, `profile`, and `test` commands from `%sqlcmd`.
Closes #519 
----
:books: Documentation preview :books:: https://jupysql--852.org.readthedocs.build/en/852/
=> add `--schema` to %sqlcmd commands

CHANGELOG.md, src/sql/plot.py
Renamed con -> conn for uniformity
Closes #759
----
:books: Documentation preview :books:: https://jupysql--863.org.readthedocs.build/en/863/
=> Renamed con to conn for uniform naming (Issue#759)

CHANGELOG.md, doc/community/developer-guide.md, src/sql/display.py, src/tests/test_display.py
- Determine whether a code is run in a jupypter notebook or terminal and decide how to embed link in `Message`
- Expose link in feedback when it is shown in a terminal
- Allow `Message` to take a list as input
Closes #846 
----
:books: Documentation preview :books:: https://jupysql--861.org.readthedocs.build/en/861/
=> improve display.py module

doc/api/configuration.md, src/sql/magic.py
Rearranged code (magic.py) and documentation (configuration.md) alphabetically for uniformity
Closes #868 
----
:books: Documentation preview :books:: https://jupysql--869.org.readthedocs.build/en/869/
=> Rearranged code and documentation alphabetically for uniformity

src/tests/integration/test_generic_db_operations.py
using [snowflake](https://github.com/ploomber/jupysql/actions/runs/6114228487/job/16595383276#step:6:1309) and [redshift](https://github.com/ploomber/jupysql/actions/runs/6114228487/job/16595383276#step:6:1314) fails in `test_sqlplot_using_schema` function. It passed in a PR but continues to fail when the PR is merged
So I changed `CREATE` to `CREATE ~ IF NOT EXISTS` to deal with snowflake error and added `pytest.mark.xfail` for redshift
Closes #X
----
:books: Documentation preview :books:: https://jupysql--872.org.readthedocs.build/en/872/
=> fix schema error in integration

doc/integrations/questdb.ipynb
- Added a note that QuestDB now supports a connection string
Closes #457 
----
:books: Documentation preview :books:: https://jupysql--889.org.readthedocs.build/en/889/
=> 457 Update QuestDB Integration Guide

CHANGELOG.md, setup.py, src/sql/cmd/snippets.py, src/sql/store.py, src/tests/test_magic_cmd.py
Fixing bug: Cannot delete a snippet after the snippet it is dependent on is force deleted.
Closes #717 
----
:books: Documentation preview :books:: https://jupysql--896.org.readthedocs.build/en/896/
=> dependent snippet deletion bug fix

CHANGELOG.md, doc/jupyterlab/sharing.md, setup.py, src/sql/_testing.py, src/sql/store.py, src/tests/test_command.py, src/tests/test_magic_cte.py
Fix bug: when comments are added in the CTE query the comments should be appended after the right bracket.
This PR handles single and multiline comments.
Closes #886 
----
:books: Documentation preview :books:: https://jupysql--894.org.readthedocs.build/en/894/
=> comment in cte

CHANGELOG.md, src/sql/parse.py, src/tests/test_parse.py
- Fixed bug where jupysql + duckdb breaks when passing :NUMBER in string slicing notation
- Added function `escape_string_slicing_notation(query)` which escapes occurrences of :NUMBER 
e.g. 'hello'[:2] --> 'hello'[\:2]
Closes #901 
----
:books: Documentation preview :books:: https://jupysql--910.org.readthedocs.build/en/910/
=> 901 jupysql + duckdb breaks if passing `:NUMBER`

CHANGELOG.md, doc/api/configuration.md, doc/jupyterlab/sharing.md, doc/user-guide/connection-file.md, src/sql/exceptions.py, src/sql/magic.py, src/sql/util.py, src/tests/test_config.py
Closes #880 
----
:books: Documentation preview :books:: https://jupysql--899.org.readthedocs.build/en/899/
=> allow configuration in the home directory

doc/integrations/clickhouse.ipynb
Typo fix: followig -> following
Closes #909 
----
:books: Documentation preview :books:: https://jupysql--916.org.readthedocs.build/en/916/
=> Fixed typo in docs/integration/clickhouse

CHANGELOG.md, src/sql/util.py, src/tests/integration/test_generic_db_operations.py, src/tests/test_magic.py
- When running integration tests for https://github.com/ploomber/jupysql/pull/912 I noticed that querying a snippet using an invalid function or invalid snippet name on a DuckDB native connection results in an uncaught CatalogException.
- Edited `util.py` to catch the phrase "Catalog Error" as a specific non-SQLAlchemy error
- Removed xfail from duckdb_native test cases in `test_generic_db_operations.py`::test_query_snippet_invalid_function_error_message
Closes #919 
----
:books: Documentation preview :books:: https://jupysql--920.org.readthedocs.build/en/920/
=> 919 DuckDB Native uncaught CatalogException

CHANGELOG.md, src/sql/error_handler.py, src/tests/test_magic.py
- Edited `_snippet_typo_error_message` in `error_handler.py` to check if the snippet is spelled correctly before returning the snippet typo error message. Previously, it assumed the would show the error message even if the snippet were spelled correctly. 
- The bug described in #940 occurred because any table misspelling, when included in a query that also uses snippets, was treated as a snippet misspelling automatically. JupySQL still checks for snippet misspellings first, but now if the snippet is spelled correctly, it doesn't return any snippet error message and instead returns the correct "Table __ Not Found" error message.
Closes #940 
----
:books: Documentation preview :books:: https://jupysql--942.org.readthedocs.build/en/942/
=> 940 Confusing error message when table does not exist

CHANGELOG.md, src/sql/command.py, src/sql/magic_cmd.py, src/sql/parse.py, src/sql/util.py, src/tests/conftest.py, src/tests/test_parse.py, src/tests/test_plot.py, src/tests/test_util.py
1. Created a guard `check_duplicate_arguments` in `src/sql/util.py`.
2. Used the guard to check for duplicates when parsing in `SQLCommand`, `SQLPlotCommand` and `SQLCmdMagic` classes.
3. Created tests for `check_duplicate_arguments`.
4. Added tests to `test_magic_args` for the improved implementation.
5. Implemented logic to prevent aliases of arguments being used with them unless forbidden.
Closes #806 
----
:books: Documentation preview :books:: https://jupysql--908.org.readthedocs.build/en/908/
=> Added guards to check and raise errors when arguments are entered twice in `%sql`, `%sqlcmd` and `%sqlplot`

CHANGELOG.md, src/sql/magic.py, src/sql/util.py, src/tests/test_config.py, src/tests/test_magic.py
1. Modified `util.get_user_config` to return a boolean representing the successful setting of user defined configurations. Returns `True` if successful and `False` if not.
2. `magic.set_configs` now looks at the success state and behaves the same as it did only if successful config was set. If there was a failure in setting configurations, it skips tasks and returns the table rows as well as the success state.
3. The `magic.load_SqlMagic_configs` function now first looks for the user configurations in the following order:
- First in `pyproject.toml` in the project root directory
- Second in `~/.jupysql/config` if no `pyproject.toml` present
- In case `pyproject.toml` is present but is missing the SqlMagic section, the user configurations are searched for in the `~/.jupysql/config`.
4. …
=> [Fix 911] Search for config in ~/.jupysql/config if pyproject.toml does not have a SqlMagic section

src/sql/parse.py, src/tests/test_magic.py, src/tests/test_parse.py
- In `parse.py`, changed `split_args_and_sql()` to run anytime a SQL command is found, rather than only when JSON arrow operators are used
- This avoids corner cases where `-` is used to indicate a negative number in `SELECT` queries
- Added some spaces to `magic_args` to improve readability
- Added tests to verify correctness
- Added no-changelog label since this is a corner case of the other PR #918 
Closes #958 
----
📚 Documentation preview 📚: https://jupysql--964.org.readthedocs.build/en/964/
=> 958 Unrecognized Argument on negative number queries

.github/workflows/ci-integration-db-sqlalchemy-v1.yaml, .github/workflows/ci.yaml, doc/community/developer-guide.md, noxfile.py, setup.py, src/tests/integration/test_generic_db_operations.py
Related to issue #983 
This fixes the SqlAlchemy v1 CI. 
Removes Snowflake and Redshift workflow.
Closes #984 
----
📚 Documentation preview 📚: https://jupysql--982.org.readthedocs.build/en/982/
=> Removed cloud tests workflow

src/sql/util.py, src/tests/test_config.py
This PR refactors `sql.util.get_user_configs()` to more specifically target only the config section `[tool.jupysql.SqlMagic]`.
When searching for "jupysql", a hint (instead of an error) will be displayed only if there is exact case-insensitive match (such as "jupySql"). We are making this stricter, because we cannot anticipate the naming of other tools in the general `tool` namespace.
A `close_match` is still used for "SqlMagic", so we detect things like "SqlMagic**s**". If found, such things will continue to throw an error with a hint, because we are now in the `jupysql` namespace.
Because the logic differs slightly at each level, I revised the structure to be a direct linear derival of the key we need, rather than the more generic toml loop search implementation. This enhances …
=> Refactor close-matching when reading toml config

src/sql/ggplot/facet_wrap.py
It's a silly little thing that I noticed when looking at something else.  The `facet` class in `ggplot/facet_wrap.py` was missing the `self` argument in its `__init__` method.  This wasn't an issue, since this class is never used directly.  Only its subclass, `facet_wrap` is used, which has its own functional `__init__` method, which doesn't call the superclass method.  Since the method supposed to do anything, I just removed it.
I'm not sure why flake8 or black didn't raise a fuss about this.
Closes #X
----
📚 Documentation preview 📚: https://jupysql--999.org.readthedocs.build/en/999/
=> Fix buggy __init__ method

CHANGELOG.md, setup.py
Remove sqlalchemy upper bound as the issue that documented the reason (#1001) seems to have been closed. 
Closes #1001
----
📚 Documentation preview 📚: https://jupysql--1020.org.readthedocs.build/en/1020/
=> Remove sqlalchemy upper bound

CHANGELOG.md, doc/integrations/duckdb.md, src/sql/connection/connection.py, src/tests/integration/test_duckDB.py, src/tests/test_connection.py
Closes #1033
----
📚 Documentation preview 📚: https://jupysql--1040.org.readthedocs.build/en/1040/
=> duckdb frame scanning fix

CHANGELOG.md, src/sql/run/sparkdataframe.py, src/sql/util.py
1. Updated is_non_sqlalchemy_error to handle pyspark.sql.utils.AnalysisException, thus when `short_errors` is enabled to show only the spark sql error and not the full stack trace
Closes #[1011](https://github.com/ploomber/jupysql/issues/1011)
----
📚 Documentation preview 📚: https://jupysql--1024.org.readthedocs.build/en/1024/
=> 1011 Disable full stack trace when using spark connect

.github/workflows/ci.yaml, .readthedocs.yml, CHANGELOG.md, doc/howto.md, scripts/large-table-gen.py, src/sql/__init__.py, src/sql/column_guesser.py, src/sql/magic.py, src/tests/test_magic.py
Closes #1047 
-  [X] Performed a self-review of my code
----
📚 Documentation preview 📚: https://jupysql--1048.org.readthedocs.build/en/1048/
=> don't use `%[%]sql` within Databricks

CHANGELOG.md, src/sql/connection/connection.py, src/sql/exceptions.py, src/sql/inspect.py, src/sql/magic.py, src/sql/magic_plot.py, src/sql/plot.py, src/sql/store.py, src/tests/test_magic.py, src/tests/test_magic_cmd.py, src/tests/test_magic_plot.py, src/tests/test_syntax_errors.py
Closes #X
----
📚 Documentation preview 📚: https://jupysql--1051.org.readthedocs.build/en/1051/
=> no longer show slack link in error messages
